#pragma once
#include <vector>
#include <string>
#include <memory>
#include "renderedObject.h"
#include "mathStructs.h"
#include "renderer.h"
#include "physicsObjectStructure.h"
#include "cloudParticle.h"
#include "octree.h"
#include "frameStore.h"

// Compute method enum
enum class CloudComputeMethod {
  CPU = 0,
  BarnesHutGPU = 1
};

class CloudObject
{
private:
  std::unique_ptr<FrameStore> frameStore;  // lazy-init after particle count is known
  // Particle state captured just before the first simulated frame
  std::vector<ParticleSnapshot> initialSnaps;

  // Helper: ensure frameStore exists with the right record size.
  void ensureFrameStore();

  // ── Barnes-Hut GPU resources ──
  bool   gpuInitialized{false};
  unsigned int bhProgram{0};       // compute shader program (GLuint)
  unsigned int particleSSBO{0};    // SSBO binding 2: particle pos+vel
  unsigned int treeSSBO{0};        // SSBO binding 3: octree nodes
  unsigned int bigBodySSBO{0};     // SSBO binding 4: big bodies

  // Uniform locations
  int locParticleCount{-1};
  int locNodeCount{-1};
  int locBigBodyCount{-1};
  int locG{-1};
  int locDt{-1};
  int locSoftening2{-1};
  int locHaloVFlat{-1}, locHaloRCore{-1};
  int locTheta{-1};
  int locFrameOffset{-1};

  Octree octree_;

  void initGPU();
  void destroyGPU();
  void uploadParticlesToGPU();
  void readbackParticlesFromGPU();
  void dispatchBarnesHut(const std::vector<PhysicsObjectStructure>& bigBodies, float simSpeed = 1.0f);
  // Dispatch this cloud's particles against an externally-built (shared) octree.
  // simOrigin is the shared sim frame's origin: the SSBO holds CLOUD-LOCAL
  // positions and the shader bridges frames via uFrameOffset.
  void dispatchAgainstTree(unsigned int sharedTree, int nodeCount,
                           unsigned int sharedBigBody, int bigBodyCount, float simSpeed,
                           const dvec3& simOrigin);

  // Turn a chunk-rendered galaxy into a real particle cloud (positions +
  // rotation-curve velocities from its own generator) so physics, picking and
  // the RT path work on it exactly like a hand-made cloud. If simulated data
  // already exists (a demoted galaxy), it is reused — never regenerated.
  void materializeGalaxy();

  // Shared Barnes-Hut resources: one octree spanning every simulated cloud so
  // separate formations gravitate on each other. Built/stepped in lockstep by
  // SimulateSharedForward (below). App-lifetime GPU objects.
  static unsigned int s_sharedTreeSSBO;
  static unsigned int s_sharedBigBodySSBO;
  static Octree       s_sharedOctree;

public:
  // Advance all GPU Barnes-Hut clouds one tick forward, sharing a single octree
  // so formations interact. Call once per frame, before the per-cloud Update().
  static void SimulateSharedForward(std::vector<std::unique_ptr<CloudObject>>& clouds,
                                    const std::vector<PhysicsObjectStructure>& bigBodies,
                                    Renderer& renderer);

  unsigned int timeframe{};
  RenderedObject renderedObject;
  // DOUBLE: a cloud may sit anywhere from 1 AU to universe scale (~1e15 AU),
  // where a float resolves to ~1e8 AU — coarser than an entire galaxy.
  dvec3 position;
  vec3 rotationDeg{0.0f, 0.0f, 0.0f};  // cloud orientation (Euler X/Y/Z degrees)

  // When false, the cloud is not gravity-simulated; its centre + orientation
  // are driven by timeline keyframes instead (animated on playback).
  bool simulatePhysics{true};
  std::vector<CameraKeyframe> keyframes;
  std::string name;            // display name (hierarchy); empty = "Cloud N"
  bool universeMember{false};  // generated by a universe -> grouped under it
  // Stable id v1 for universe persistence: which Create-Universe press made
  // this galaxy, and its index in that generation. -1 = not universe-made.
  int uniRecord{-1};
  int uniIndex{-1};
  // Set when a galaxy is promoted to particles: turning physics back off
  // rebuilds the cheap chunked render cache FROM THE PARTICLES (which stay —
  // after a simulation they, not the generator recipe, are the truth).
  bool demoteToChunks{false};
  // Close enough that the cheap chunked stand-in is no longer good enough:
  // render it through the ORDINARY cloud pipeline instead — the same path a
  // hand-made cloud uses, so a galaxy up close IS a normal cloud rather than
  // something tuned to resemble one.
  bool nearPromoted{false};
  // True once a physics step has actually moved this cloud's particles. A
  // clean promote->demote round-trip (nothing ever simulated) returns to the
  // recipe instead of freezing the galaxy as data.
  bool simDirty{false};
  // ── Multi-scale regime (see dynamics.h) — derived every frame, never saved ──
  // Rigid = the cloud's own dynamical time is unresolved at the current step
  // (thousands of internal orbits per frame: phase-mixed), so its particles
  // freeze and the cloud moves as ONE body: centre of mass on a Kepler orbit
  // around its parent (a heavier object or cloud), or coasting if it has none.
  int    dynParent{-1};          // -1 none; >=0 object index; <0 (-2-k) cloud k
  bool   dynRigid{false};
  double dynT{0.0};              // internal dynamical time 2π·median r / median v (yr)
  double dynMu{0.0};
  dvec3  dynRelPos0{}, dynRelVel0{};
  double dynElapsed{0.0};
  dvec3  dynComVel{};            // mean particle velocity, world frame (the cloud's drift)
  dvec3  dynComWorld{};          // centre of mass, world frame
  double dynMass{0.0};           // total particle mass
  int    dynTCounter{0};         // T/COM/mass are O(n): refreshed every few frames
  std::string formationFile;  // empty = procedural generation
  CloudComputeMethod computeMethod{CloudComputeMethod::BarnesHutGPU};
  float barnesHutTheta{0.5f};
  float temperature{4500.f};      // Kelvin — blackbody colour for particles
  int   renderMode{0};            // 0=Points, 1=Nebula
  float nebulaScatterScale{0.4f}; // Beer-Lambert dTau multiplier (nebula mode)
  float particleSizeSpread{0.0f}; // 0=uniform radius, 1=multi-scale mix (clumpiness)
  float scale{1.0f};              // virial scale applied at spawn time (stored for inspector sync)

  void applyVirialScale(float s); // scale positions by s, velocities by 1/sqrt(s)
  void Update(Renderer& renderer, const std::vector<PhysicsObjectStructure>& physicsObjects);

  // Procedural generation constructor (existing)
  CloudObject(const vec3& position, int objectCount, float (*distributionFunc)(float x, float y, float z), const vec3& size);

  // Formation file constructor
  CloudObject(const vec3& position, const std::string& formationPath);

  // Direct particle constructor (procedural generation)
  CloudObject(const vec3& position, std::vector<CloudParticle> particles);

  ~CloudObject();

  void SetShaders(const std::string& vertShaderPath,const std::string& fragShaderPath);
  // Returns the number of live particles (for UI display)
  int particleCount() const { return renderedObject.cloudParticleCount(); }

  // Centroid and bounding radius of the particle cloud (world space)
  // WORLD-space centre and radius, in double. Callers use this to aim the
  // camera, so it must be absolute: returning cloud-LOCAL coordinates (as this
  // once did) sends Locate to the origin for anything not sitting there.
  void boundsEstimate(dvec3& center, double& radius) const;

  // World-space centre of mass + total mass of the particles. Returns false if
  // the cloud is empty. Lets the cloud pull back on the big bodies (one COM
  // point mass), the reciprocal of big bodies pulling on cloud particles.
  bool gravitySource(vec3& comWorld, float& totalMass) const;

  // Timeline accessors
  unsigned int getTimeframe() const { return timeframe; }
  unsigned int getBufferSize() const { return frameStore ? static_cast<unsigned int>(frameStore->totalFrames()) : 0u; }
  void setTimeframeAndRestore(unsigned int frame);
  void clearRecording();
  // Scale every particle's mass so the cloud's own gravity matches its
  // velocities (GM/r = v^2 at the median radius): a formation that would fly
  // apart or collapse becomes one that holds together under simulation. The
  // ratio v_rms/v_circ it reports is 1 when balanced.
  double virialRatio() const;        // v_median / v_circ(G M_total, r_median); 0 = unknown
  void   virializeMasses();
  // Fit the halo (haloVFlat, haloRCore) to the particles' own tangential
  // speeds about their angular-momentum axis: binned medians, least squares on
  // v = vFlat·r/(r+rc). Returns false (halo left at 0) if the cloud does not
  // rotate. Runs once at load when the project carries no halo keys.
  bool   fitHaloFromVelocities();
  bool   haloResolved{false};        // set once the halo is known (from file, recipe or fit)
  // Restore the state from before the first simulated frame, then clear
  void resetToInitial();

  // Allow main loop to propagate RAM budget
  void setRamBudget(size_t bytes) { if (frameStore) frameStore->setRamBudget(bytes); }
  size_t ramBytes() const { return frameStore ? frameStore->ramBytes() : 0; }
  size_t recordBytes() const { return frameStore ? frameStore->recordSize() : 0; }
};
